CREATE TABLE boardposition (id INT NOT NULL AUTO_INCREMENT, positionuid DECIMAL(58, 0), winwhite INT, numdraw INT, winblack INT, PRIMARY KEY (id), UNIQUE(positionuid))
CREATE TABLE futureposition (id INT NOT NULL AUTO_INCREMENT, positionfrom INT, movestr INT, positionto INT, PRIMARY KEY (id), UNIQUE (positionfrom, movestr))
CREATE TABLE player (id INT NOT NULL AUTO_INCREMENT, fullname VARCHAR(30), higherelo INT, numwin INT, numdraw INT, numloose INT, realplayerid INT, normalizedname VARCHAR(30), PRIMARY KEY (id), UNIQUE(normalizedname))
CREATE INDEX player0 ON player (fullname ASC)
CREATE INDEX player1 ON player (realplayerid ASC)
CREATE TABLE playeralias (id INT NOT NULL, numwin INT, numdraw INT, numloose INT, PRIMARY KEY (id))
CREATE TABLE gameheader (id INT NOT NULL AUTO_INCREMENT, whiteplayerid INT, whiteelo SMALLINT, blackplayerid INT, blackelo SMALLINT, finalresult SMALLINT, eventname VARCHAR(30), sitename VARCHAR(30), eventdate DATE, roundnr VARCHAR(8), chessecoid SMALLINT, startingpositionid INT, startingmovenr SMALLINT, startingcolortomove SMALLINT, gamehash VARCHAR(22), gameinstats TINYINT(1), PRIMARY KEY (id), UNIQUE(gamehash))
CREATE INDEX gameheader0 ON gameheader (whiteplayerid ASC)
CREATE INDEX gameheader1 ON gameheader (blackplayerid ASC)
CREATE INDEX gameheader2 ON gameheader (chessecoid ASC)
CREATE INDEX gameheader3 ON gameheader (gameinstats ASC, finalresult ASC)
CREATE TABLE gamedetail (id INT NOT NULL AUTO_INCREMENT, gameheaderid INT NOT NULL, futurepositionid INT, PRIMARY KEY (id, gameheaderid))
CREATE INDEX gamedetail0 ON gamedetail (futurepositionid ASC, gameheaderid ASC)
CREATE INDEX gamedetail1 ON gamedetail (gameheaderid ASC, id ASC)
CREATE TABLE chesseco (id SMALLINT NOT NULL AUTO_INCREMENT, code VARCHAR(3), winwhite INT, numdraw INT, winblack INT, PRIMARY KEY (id), UNIQUE(code))
CREATE TABLE positionnote (positionid INT NOT NULL, notetype SMALLINT, notecnt VARCHAR(2000), PRIMARY KEY (positionid))
CREATE TABLE favoritesgames (gameheaderid INT NOT NULL, valuationrate SMALLINT, PRIMARY KEY (gameheaderid))