CREATE TABLE boardposition (id SERIAL PRIMARY KEY, positionuid VARCHAR(25), winwhite INT, numdraw INT, winblack INT, UNIQUE(positionuid))
CREATE TABLE futureposition (id SERIAL PRIMARY KEY, positionfrom INT, movestr INT, positionto INT, UNIQUE (positionfrom, movestr))
CREATE TABLE player (id SERIAL PRIMARY KEY, fullname VARCHAR(30), higherelo INT, numwin INT, numdraw INT, numloose INT, realplayerid INT, normalizedname VARCHAR(30), UNIQUE(normalizedname))
CREATE INDEX player0 ON player (fullname)
CREATE INDEX player1 ON player (realplayerid)
CREATE TABLE playeralias (id int PRIMARY KEY, numwin INT, numdraw INT, numloose INT)
CREATE TABLE gameheader (id SERIAL PRIMARY KEY, whiteplayerid INT, whiteelo SMALLINT, blackplayerid INT, blackelo SMALLINT, finalresult SMALLINT, eventname VARCHAR(30), sitename VARCHAR(30), eventdate DATE, roundnr VARCHAR(8), chessecoid SMALLINT, startingpositionid INT, startingmovenr SMALLINT, startingcolortomove SMALLINT, gamehash VARCHAR(22), gameinstats SMALLINT, UNIQUE(gamehash))
CREATE INDEX gameheader0 ON gameheader (whiteplayerid)
CREATE INDEX gameheader1 ON gameheader (blackplayerid)
CREATE INDEX gameheader2 ON gameheader (chessecoid)
CREATE INDEX gameheader3 ON gameheader (gameinstats ASC, finalresult ASC)
CREATE TABLE gamedetail (id SERIAL, gameheaderid INT NOT NULL, futurepositionid INT, PRIMARY KEY (id, gameheaderid))
CREATE INDEX gamedetail0 ON gamedetail (futurepositionid, gameheaderid)
CREATE INDEX gamedetail1 ON gamedetail (gameheaderid ASC, id ASC)
CREATE TABLE chesseco (id SMALLSERIAL PRIMARY KEY, code VARCHAR(3), winwhite INT, numdraw INT, winblack INT, UNIQUE(code))
CREATE TABLE positionnote (positionid INT PRIMARY KEY, notetype SMALLINT, notecnt VARCHAR(2000))
CREATE TABLE favoritesgames (gameheaderid INT PRIMARY KEY, valuationrate SMALLINT)